import { describe, expect, it } from "vitest";
import { renderPluginPrefsDts } from "./prefs.js";

describe("renderPluginPrefsDts", () => {
  it("should render plugin's dts", () => {
    const prefs = {
      "test.string": "hello",
      "test.number": 42,
    };

    const result = `// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "test.string": string;
      "test.number": number;
    };
  }
}
`;
    expect(renderPluginPrefsDts(prefs)).toBe(result);
  });
});
