// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "string": string;
      "boolean": boolean;
      "number": number;
      "break-line": string;
      "fake-number": string;
      "templateLiteral": string;
      "long-number": number;
    };
  }
}
