export function generateMochaSetup(options: {
  port: number;
  timeout: number;
  abortOnFail: boolean;
  exitOnFinish: boolean;
}) {
  return `// Generated by zotero-plugin-scaffold
mocha.setup({ ui: "bdd", reporter: Reporter, timeout: ${options.timeout} || 10000, });

window.expect = chai.expect;
window.assert = chai.assert;

async function send(data) {
  console.log("Sending data to server", data);
  const req = await Zotero.HTTP.request(
    "POST",
    "http://localhost:${options.port}/update",
    {
      body: JSON.stringify(data),
    }
  );

  if (req.status !== 200) {
    dump("Error sending data to server" + req.responseText);
    return null;
  } else {
    const result = JSON.parse(req.responseText);
    return result;
  }
}

window.debug = function (...data) {
  const str = data.join("\\n");
  Zotero.debug(str);
  send({ type: "debug", data: { str } });
};

// Inherit the default test settings from Zotero
function Reporter(runner) {
  var indents = 0,
    passed = 0,
    failed = 0,
    aborted = false;

  function indent() {
    return Array(indents).join("  ");
  }

  function dump(str) {
    console.log(str);
    document.querySelector("#mocha").innerText += str;
  }

  runner.on("start", async function () {
    await send({ type: "start" });
  });

  runner.on("suite", async function (suite) {
    ++indents;
    const str = indent() + suite.title + "\\n";
    dump(str);
    await send({ type: "suite", data: { title: suite.title, str } });
  });

  runner.on("suite end", async function (suite) {
    --indents;
    const str = indents === 1 ? "\\n" : "";
    dump(str);
    await send({ type: "suite end", data: { title: suite.title, str } });
  });

  runner.on("pending", async function (test) {
    const str = indent() + "pending  -" + test.title + "\\n";
    dump(str);
    await send({ type: "pending", data: { title: test.title, str } });
  });

  runner.on("pass", async function (test) {
    passed++;
    let str = indent() + Mocha.reporters.Base.symbols.ok + " " + test.title;
    if ("fast" != test.speed) {
      str += " (" + Math.round(test.duration) + " ms)";
    }
    str += "\\n";
    dump(str);
    await send({
      type: "pass",
      data: { title: test.title, duration: test.duration, str },
    });
  });

  runner.on("fail", async function (test, err) {
    // Make sure there's a blank line after all stack traces
    err.stack = err.stack.replace(/\\s*$/, "\\n\\n");

    failed++;
    let indentStr = indent();
    const str =
      indentStr +
      // Dark red X for errors
      "\\x1B[31;40m" +
      Mocha.reporters.Base.symbols.err +
      " [FAIL]\\x1B[0m" +
      // Trigger bell if interactive
      (Zotero.automatedTest ? "" : "\\x07") +
      " " +
      test.title +
      "\\n" +
      indentStr +
      "  " +
      err.message +
      " at\\n" +
      err.stack.replace(/^/gm, indentStr + "    ").trim() +
      "\\n\\n";
    dump(str);

    if (${options.abortOnFail ? "true" : "false"}) {
      aborted = true;
      runner.abort();
    }

    await send({
      type: "fail",
      data: { title: test.title, stack: err.stack, str },
    });
  });

  runner.on("end", async function () {
    const str =
      passed +
      "/" +
      (passed + failed) +
      " tests passed" +
      (aborted ? " -- aborting" : "") +
      "\\n";
    dump(str);

    await send({
      type: "end",
      data: { passed: passed, failed: failed, aborted: aborted, str },
    });

    // Must exit on Zotero side, otherwise the exit code will not be 0 and CI will fail
    if (${options.exitOnFinish ? "true" : "false"}) {
      Zotero.Utilities.Internal.quit(0);
    }
  });
}
`;
}

export function generateHtml(
  setupCode: string,
  testFiles: string[],
) {
  const tests = testFiles.map(f => `<script src="${f}"></script>`).join("\n    ");

  return `
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8"></meta>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
    <title>Zotero Plugin Test</title>
    <style>
        html {
            min-width: 400px;
            min-height: 600px;
        }
        body {
            font-family: Arial, sans-serif;
        }
    </style>
</head>
<body>
    <div id="mocha"></div>

    <!-- Include Zotero Vars -->
    <script src="chrome://zotero/content/include.js"></script>

    <!-- Mocha and Chai Libraries -->
    <script src="mocha.js"></script>
    <script src="chai.js"></script>

    <!-- Setup Mocha -->
    <script>
      ${setupCode}
    </script>

    <!-- Unit tests -->
    ${tests}

    <!-- Run Mocha -->
    <script class="mocha-exec">
      mocha.run();
    </script>
</body>
</html>
`;
}
